Repository rserial/flintpy, pull requests merged in 2024-07, with the labels that each got.

#11 Add jupyter notebooks linterns
  .gitignore
  .jupyter/jupyter_lab_config.py
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  poetry.lock
  pyproject.toml
  tasks.py
  templates/experiments/Sample.ipynb
Labels: dependencies, python

#12 Fix citation file
  .github/CODEOWNERS
  CITATION.cff
Labels: bug, documentation

#13 Feature add pyflint code
  README.md
  poetry.lock
  pyproject.toml
  src/flintpy/flintpy.py
  src/flintpy/kernels.py
  src/flintpy/plotting.py
  src/flintpy/utils.py
Labels: enhancement, python

#14 Fix naming
  README.md
  src/flintpy/plotting.py
  src/flintpy/utils.py
Labels: bug
